внес изменения в авторизацию
MaximMaslovVik/14_sprint pull request #1
Opened 2020-01-19 22:25 UTC by MaximMaslovVik

2020-01-20 09:30 UTC, aarefiev reviewed
Хорошо. Есть несколько ошибок.

Нужно исправить:
1. Не запускается линтер.
2. Сервер падает при запуске.
3. Нельзя создать пользователя или залогиниться.
4. `login` и `createUser` не объявлены.
5. Остался хардкод из 13-й практики.
6. Мидлвара `auth` не работает.
7. Остался доступен роут `POST /users`.
8. Не работают роуты для `/cards`.

Комментарий к ошибке "Не запускается линтер":
При попытке запустить команду линтинга `npx eslint --ext .js .` возникает ошибка:
```bash
$ npx eslint --ext .js .
No ESLint configuration found in ~/14_sprint.
```
Ожидаемый результат - линтер запускается, ошибок маркерованных **error** нет (**warning** допускается).
В 12-й и 13-й практиках добавляли `.eslintrc` в проект. Можно взять тот, который есть в 13-й практике:
https://github.com/MaximMaslovVik/13_sprint/blob/dev/.eslintrc .

Комментарий к ошибке "Не работают роуты для `/cards`":
https://github.com/MaximMaslovVik/14_sprint/blob/66a1093dd9f57c4561fd54b9cd875d6783ad4056/routes/cards.js#L2
Контроллер экспортирует функции с другими названиями:
- вместо `cardsAll` экспортируется `getAllCards`,
- вместо `cardCreate` экспортируется `createCard`

2020-01-20 09:30 UTC, aarefiev commented on controllers/users.js
> +const User = require(../models/user);
Нужно исправить: сервер падает при запуске.
Функция `require()` требует, чтобы имя модуля или путь был строкой. В JavaScript все строки следует писать в кавычках (одинарные или двойные).

2020-01-20 09:30 UTC, aarefiev commented on app.js
> +app.post('/signup', createUser);
Нужно исправить: нельзя создать пользователя или залогиниться.
Для `express` важен порядок определения мидлвар (роуты - это по сути тоже мидлвары). Рассмотрим:
https://github.com/MaximMaslovVik/14_sprint/blob/66a1093dd9f57c4561fd54b9cd875d6783ad4056/app.js#L18-L26

Первым делом назначается мидлвара `auth`. Она проводит проверку существования токена в запросе. Если он не существует - останавливает работу и отдает статус 401.
Далее идёт обработка тела запроса - это `bodyParser.json()` и `bodyParser.urlencoded()`.
Далее идут роуты `/users` и `/cards`. 
И в самом конце роуты `/signin` и `/signup`.

В задании сказано, что авторизацией будут покрыты только роуты `/users` и `/cards`. Для этого необходимо перенести роуты `/signin` и `/signup` так, чтобы они были объявлены до назначения мидлвары `auth`. Примерный вариант решения:
```js
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.post('/signin', login);
app.post('/signup', createUser);

// все роуты после этой мидлвары будут требовать авторизацию
app.use(auth);
app.use('/', users);
app.use('/', cards);
```

2020-01-20 09:30 UTC, aarefiev commented on app.js
>  });
Нужно исправить: остался хардкод из 13-й практики.
В 13-й практике эта мидлвара была добавлена специально. Это временное решение для авторизации. Сейчас же за авторизацию отвечает мидлвара [auth](https://github.com/MaximMaslovVik/14_sprint/blob/66a1093dd9f57c4561fd54b9cd875d6783ad4056/middlewares/auth.js).

2020-01-20 09:30 UTC, aarefiev commented on middlewares/auth.js
> +    payload = jwt.verify(token, JWT_SECRET);
Нужно исправить: мидлвара `auth` не работает.
Это связано с тем, что в момент авторизации выдается токен, который кодируется с одним секретным ключом:
https://github.com/MaximMaslovVik/14_sprint/blob/66a1093dd9f57c4561fd54b9cd875d6783ad4056/controllers/users.js#L41
А мидлвара `auth` ожидает, что будет уже совсем другой ключ:
https://github.com/MaximMaslovVik/14_sprint/blob/66a1093dd9f57c4561fd54b9cd875d6783ad4056/middlewares/auth.js#L5

Нужно, чтобы JWT_SECRET был одним и тем же в обоих случаях.

2020-01-20 09:30 UTC, aarefiev commented on routes/users.js
>  router.post('/users', createUser);
Нужно исправить: доступен роут `POST /users`.
Этот роут не нужен, потому что создание пользователя было перенесено в роут `/signup`.

2020-01-20 09:30 UTC, aarefiev commented on app.js
> +app.post('/signup', createUser);
Нужно исправить: `login` и `createUser` не объявлены.
Ожидается, что они будут подключены из контроллера [/controllers/users.js](https://github.com/MaximMaslovVik/14_sprint/blob/66a1093dd9f57c4561fd54b9cd875d6783ad4056/controllers/users.js).

2020-01-22 20:09 UTC, aarefiev requested changes
Круто. Исправления хорошие, сделано очень хорошо.

Было найдено несколько критических ошибок и улучшений, которые ниже представлены в виде кратких комментариев. Ко всем есть развернутые комментарии ниже списка или непосредственно в коде.

Нужно исправить: 
1. Не запускается линтер.
2. Пользователь может удалить карточку, которую он не создавал.
3. Cервер не запускается из-за ошибки.
4. При попытке авторизоваться с коротким паролем сервер возвращает 500.

Можно лучше: 
1. Использовать авторизацию через куки.
2. Подключать секретный ключ для выпуска `jwt` токена из одного места.

---
**Развернутый комментарий к ошибке "Не запускается линтер":**

При попытке запустить команду линтинга `npx eslint --ext .js .` возникает ошибка:
```
$ npx eslint --ext .js .
No ESLint configuration found in ~/14_sprint.
```

Ожидаемый результат - линтер запускается, ошибок маркерованных **error** нет (**warning** допускается).
В 12-й и 13-й практиках добавляли `.eslintrc` в проект. Можно взять тот, который есть в 13-й практике:
https://github.com/MaximMaslovVik/13_sprint/blob/dev/.eslintrc .

2020-01-22 20:09 UTC, aarefiev commented on controllers/users.js
> +        .then((user) => {res.status(201).send({_id: user._id, email: user.email });
Нужно исправить: сервер не запускается из-за ошибки.
Ошибка:
```bash
~/14_sprint/users.js:21
        .then((user) => {res.status(201).send({_id: user._id, email: user.email });
        ^

SyntaxError: Unexpected token '.'
```
Нужно заменить текущий код на следующий:
```js
.then((hash) => User.create({ name, about, avatar, email, password: hash }))
.then(({ name, about, avatar, email }) => res.send({ name, about, avatar, email })) 
```
Это рабочий код. К тому же он выполняет все то, что нужно по заданию.

2020-01-22 20:09 UTC, aarefiev commented on controllers/users.js
> +    res.status(500).send({ message: 'Слишком короткий пароль!' });
Нужно исправить: при попытке авторизоваться с коротким паролем сервер возвращает 500.
Под код 500 всегда попадают ошибки, которые возникают на сервере. Это могут быть как SyntaxError и TypeError так и ошибки при выполнении каких-то функций (например, ошибка возникающая при попытке записи в базу данных).
Текущая ситуация:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/controllers/users.js#L18
Она не попадает до 500 код, потому что ошибки на сервере нет, сами данные, которые отправил пользователь некорректные.  А в этом случае всегда стоит отправлять код [400 Bad Request](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/400).

2020-01-22 20:09 UTC, aarefiev commented on controllers/cards.js
>  module.exports.deleteCard = (req, res) => {
Нужно исправить: пользователь может удалить карточку, которую он не создавал.
Сейчас в случае если карточка найдена она удаляется:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/controllers/cards.js#L23-L29

В практике добавилась возможность создавать нескольких пользователей. Поэтому важно, чтобы один пользователь не мог удалять карточки другого. Для этого логику работы `deleteCard` нужно адаптировать так, чтобы перед удалениям была произведена проверка существования карточки в базе и проверка пользователей. 
Например, логику можно описать в 5 пунктов, которые выполняются последовательно:
1. Пытаемся найти карточку в базе по `req.params.cardId` ([метод .findById()](https://mongoosejs.com/docs/api.html#model_Model.findById)).
2. Если значение, которое возвращается в `.then()` равно `null`, то карточки не существует в базе. Возвращаем 404 и сообщение. Это уже реализовано:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/controllers/cards.js#L25-L27
3. Проверяем является ли текущий пользователь создателем карточки. Для этого лучше всего использовать метод сравнения встроенный в библиотеку ([метод .equals()](https://mongoosejs.com/docs/api.html#query_Query-equals)):
```js
if (card.owner.equals(req.user._id) {}
```
4. Если проверка даёт ложный результат, то возвращаем 403 и сообщение, что доступ запрещен. Обязательно не забываем `return`, если ниже будет идти код, который должен выполниться в другом случае.
5. Все проверки пройдены, удаляем карточку. Повторный поиск по `cardId` здесь не нужен, можно сразу удалять ([метод .remove()](https://mongoosejs.com/docs/api.html#model_Model.remove)) и возвращать ответ (это частично реализовано):
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/controllers/cards.js#L28

2020-01-22 20:09 UTC, aarefiev commented on middlewares/auth.js
> +  let payload;
Можно лучше: использовать авторизацию через куки.
Сейчас при авторизации пользователя назначается кука, в которую сохраняется токен:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/controllers/users.js#L45-L47
Далее дополнительно отправляется токен в теле ответа:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/controllers/users.js#L48
Отправку токена в теле можно убрать, а чтобы тело ответа не было пустым, можно написать сообщение, что авторизация успешна.

Теперь по поводу того, что нужно, чтобы можно было использовать токен из куки в `auth`. Для этого необходимо сделать следующее:
1.  Установить модуль [cookie-parser](https://www.npmjs.com/package/cookie-parser#example).
2. Подключить его как указано в примере. Важно, чтобы он был подключен до назначения роутов. Лучше сразу после назначения bodyParser:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/app.js#L19-L20
3. Изменить код `auth` так, чтобы токен был взят из куки:
```js
const { token } = req.cookies;
```

2020-01-22 20:09 UTC, aarefiev commented on controllers/users.js
> +      const token = jwt.sign({ _id: user._id }, 'some-secret-key', { expiresIn: '7d' });
Можно лучше: подключать секретный ключ для выпуска `jwt` токена из одного места.
Сейчас секретный ключ зашит в файлах, где он используется. Раз:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/controllers/users.js#L45
и два:
https://github.com/MaximMaslovVik/14_sprint/blob/c26f88ed3d621824e501bbc52c21e5c5404d6be9/middlewares/auth.js#L16
В этом случае при изменении ключа возникает проблема, что нужно менять ключ непосредственно в этих файлах. Можно случайно пропустить изменение одного из мест, что повлечет за собой ошибку - авторизация не будет проходить, тк секретные ключи будут разными.

В качестве решения этой проблемы лучше всего вынести секретный ключ в отдельный файл в корне проекта, например `/config.js` и уже из него экспортировать ключ:
```js
module.exports.JWT_SECRET = 'some-secret-key';
```
Далее этот файл подключаем в файлах, где нам нужен секретный ключ и используем его через переменную:
```js
const { JWT_SECRET } = require('../config.js');
const token = jwt.sign({ _id: user._id }, JWT_SECRET, { expiresIn: '7d' });
```

2020-01-24 16:47 UTC, aarefiev requested changes
Очень круто. Огромный плюс за внесение изменений из секции можно лучше 👍 .

Практически все отлично. Есть несколько маленьких ошибок, которые нужно обязательно решить, чтобы идти дальше. Также я детально описал в секции **Можно лучше** комментарии, которые помогут сделать текущий код лучше и проще реализовать изменения в следующей практике.

Нужно исправить:
1. Ошибки линтинга. 
2. При попытке удалить чужую карточку возвращается 401.

Можно лучше:
1. Подключать секретный ключ из файла.
2. Получать `PORT` из конфигурационного файла.
3. Подключать `dotenv` при необходимости.
4. Игнорировать .env файл.
5. Дать возможность переназначить секретный ключ при запуске приложения.

---
**Развернутый комментарий к ошибке "Ошибки линтинга":**

При попытке запустить команду линтинга `npx eslint --ext .js .` линтер сообщает об ошибках:
```
$ npx eslint --ext .js .
...
✖ 22 problems (22 errors, 0 warnings)
  15 errors and 0 warnings potentially fixable with the `--fix` option.
```

_часть вывода я намеренно опустил для экономии места_

Ожидаемый результат - ошибок маркерованных **error** нет (**warning** допускается).

Самое важное в выводе - это сообщение, что линтер может сам поправить часть ошибок (**15 errors and 0 warnings potentially fixable with the `--fix` option.**). Поэтому сделаем так, как предлагает линтер:
```
$ npx eslint --fix --ext .js .
```

Оставшиеся  7 ошибок придется исправить вручную.

2020-01-24 16:47 UTC, aarefiev commented on app.js
> +require('dotenv').config();
Можно лучше: подключать `dotenv` при необходимости.
Напомню, модуль `dotenv` автоматически подключает `.env` файл, если его добавить в корень проекта. При подключении переменные, которые записаны в `.env` файле будут доступны из `process.env`. Далее уже работаем с `process.env`. Чтобы этого достичь, нужно подключить модуль как можно раньше.

Рассмотрим код: 
```js
require('dotenv').config();
```

В `nodemon` можно сделать так, чтобы этот модуль подключился до запуска скрипта. Для этого достаточно добавить выполнение кода перед запуском скрипта:
https://github.com/MaximMaslovVik/14_sprint/blob/5747b8bdedcda318262cbed30f26537ac525a6ef/package.json#L8
```bash
nodemon --exec 'node -r dotenv/config' app.js
```

Подробнее: https://github.com/remy/nodemon#running-non-node-scripts .

2020-01-24 16:47 UTC, aarefiev commented on .env
> +JWT_SECRET=b24076852c7c534c77ce7b233022026ffc663393b557432496f2a70fa3756b33
Можно лучше: игнорировать `.env` файл.
Этот файл нужен только для локальной разработки. Обычно здесь содержатся секретные ключи или что-то, что влияет на работу проекта. Но эти данные опциональные.

В текущей ситуации в следующей практике будет проблема с секретками. Может быть ошибка, что секретный ключ на продакшене аналогичен ключу в разработке.

2020-01-24 16:47 UTC, aarefiev commented on secret.js
> +module.exports.JWT_SECRET = 'b24076852c7c534c77ce7b233022026ffc663393b557432496f2a70fa3756b33';
Можно лучше: дать возможность переназначить секретный ключ при запуске приложения.
Сейчас секретный ключ зашит и не может быть изменен без изменения этого файла. Бывает ситуации, когда необходимо, чтобы этот ключ можно было изменить без изменения кода. В этом случае нам хорошо помогают ENV переменные, они могут устанавливаться для приложения до запуска. 

Здесь лучше всего добавить задел на будущее и написать так:
```js
module.exports.JWT_SECRET = process.env.JWT_SECRET || 'b24076852c7c534c77ce7b233022026ffc663393b557432496f2a70fa3756b33';
```

Т.е. если секретный ключ будет установлен в ENV, то будет использоваться он, иначе - используем значение из кода файла.

**В дополнение:** для разработки можно не указывать такой сложный секретный ключ, достаточно любой строки типа:
```js
module.exports.JWT_SECRET = process.env.JWT_SECRET || 'secret key';
```

2020-01-24 16:47 UTC, aarefiev commented on app.js
>  const { PORT = 3000 } = process.env;
Можно лучше: получать `PORT` из конфигурационного файла.
Например отсюда:
https://github.com/MaximMaslovVik/14_sprint/blob/5747b8bdedcda318262cbed30f26537ac525a6ef/secret.js

2020-01-24 16:47 UTC, aarefiev commented on controllers/users.js
> +      const JWT_SECRET = 'b24076852c7c534c77ce7b233022026ffc663393b557432496f2a70fa3756b33';
Можно лучше: подключать секретный ключ из файла.
Отсюда:
https://github.com/MaximMaslovVik/14_sprint/blob/5747b8bdedcda318262cbed30f26537ac525a6ef/secret.js#L1
Т.е: достаточно расскомментировать эту строку:
https://github.com/MaximMaslovVik/14_sprint/blob/5747b8bdedcda318262cbed30f26537ac525a6ef/controllers/users.js#L6

2020-01-24 16:47 UTC, aarefiev commented on middlewares/auth.js
> +  const JWT_SECRET = 'b24076852c7c534c77ce7b233022026ffc663393b557432496f2a70fa3756b33';
Можно лучше: подключать секретный ключ из файла.
Отсюда:
https://github.com/MaximMaslovVik/14_sprint/blob/5747b8bdedcda318262cbed30f26537ac525a6ef/secret.js#L1
Т.е: достаточно расскомментировать эту строку:
https://github.com/MaximMaslovVik/14_sprint/blob/5747b8bdedcda318262cbed30f26537ac525a6ef/middlewares/auth.js#L6

2020-01-24 16:47 UTC, aarefiev commented on controllers/cards.js
> +        return res.status(401).send({ message: 'Вы не имеете доступ к удалению чужих карточек' });
Нужно исправить: при попытке удалить чужую карточку возвращается 401.
[401 Unauthorized](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/401) - это код, который возвращается при отклонении авторизации. Обычно, когда логин/пароль (или если авторизация по токену, то токен) не верен.
Но в REST есть специальный код, который отвечает за ограничение доступа к ресурсу. Это код [403 Forbidden](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/403).

В текущей ситуации у нас как раз ограничение доступа на удаление. Поэтому нужно возвращать 403.

2020-01-25 06:44 UTC, aarefiev requested changes
Отлично. Все здорово. Отдельный плюс за, внесение изменений из секции **Можно лучше** :+1:. 

Как я понял, некоторые комментарии из этой секции не совсем детально объясняны, поэтому те, которые были пропущены/или выполнены не до конца я добавил повторно и детально расписал.

Также в результате последних изменений была допущена одна ошибка, добавил ее.

**Нужно исправить:** при попытке удалить существующую собственную карточку, карточка удаляется и возвращается 403.

**Можно лучше:**
1. Игнорировать `.env` файл.
2. Получать `PORT` из конфигурационного файла.
3. Удалить неиспользуемое.

2020-01-25 06:44 UTC, aarefiev commented on .env
> +JWT_SECRET=b24076852c7c534c77ce7b233022026ffc663393b557432496f2a70fa3756b33
Можно лучше: игнорировать `.env` файл.
Этот файл нужен только для локальной разработки. Обычно здесь содержатся секретные ключи или что-то, что влияет на работу проекта. Но эти данные опциональные.

В текущей ситуации в следующей практике будет проблема с секретками. Может быть ошибка, что секретный ключ на продакшене аналогичен ключу в разработке.

Чтобы его убрать из репозитория нужно сделать следующее:
**1. Удалить файл из индекса:**

Просто удалить файл не получится, этот файл был уже проиндексирован `git`. Для таких ситуаций существует команда `git rm --cached <file>`. Удаляем:
```bash
$ git rm --cached .env
```

Команда не удаляет физически файл, а удаляет лишь его проиндексированную копию. Это можно увидеть, если выполнить команду `git status`:
```bash
$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    .env

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.env
```

**2. Добавить файл в список игнорирования** (файл `.gitignore`). Например дописав:
```bash
# environment
.env
``` 

После добавления нужно закоммитить изменения и запушить в репозиторий.

2020-01-25 06:44 UTC, aarefiev commented on app.js
> +require('dotenv').config();
Можно лучше: удалить неиспользуемое.
Сейчас конфиг подключается перед запуском скрипта:
https://github.com/MaximMaslovVik/14_sprint/blob/dev/package.json#L8
Поэтому повторно нет необходимости подключать.

2020-01-25 06:44 UTC, aarefiev commented on routes/users.js
> +router.post('/signin', login);
Можно лучше: удалить неиспользуемое.
Роут авторизации уже был назначен выше:
https://github.com/MaximMaslovVik/14_sprint/blob/080528a90bd2913742e9e12da5f5ff54d82079ec/app.js#L30
Повторно не нужно переопределять роут. Это может привести к ошибкам.

2020-01-25 06:44 UTC, aarefiev commented on app.js
>  const { PORT = 3000 } = process.env;
Можно лучше: получать `PORT` из конфигурационного файла.

Достаточно дописать экспортирование `PORT` в файл [secret.js](https://github.com/MaximMaslovVik/14_sprint/blob/080528a90bd2913742e9e12da5f5ff54d82079ec/secret.js):
```js
module.exports.PORT = process.env.PORT || 3000;
```
и получить `PORT` в `app`:
```js
const { PORT } = require('../secret');
```

2020-01-25 06:44 UTC, aarefiev commented on controllers/cards.js
> +      } return res.status(403).send({ message: 'Вы не имеете доступ к удалению чужих карточек' });
Нужно исправить: при попытке удалить существующую собственную карточку, карточка удаляется и возвращается 403.
Ошибка связана с тем, что в условии, когда доступ разрешен нет выхода из функции. И следующий код выполняется всегда, независимо от условия выше:
https://github.com/MaximMaslovVik/14_sprint/blob/080528a90bd2913742e9e12da5f5ff54d82079ec/controllers/cards.js#L35

Нужно остановить выполнение функции, добавив `return` внутрь условия:
```js
if (card.owner.toString() === ownerId) {
  // останавливаем выполнение после удаления
  return Card.findByIdAndRemove(cardId)
    .then((cardI) => res.send({ data: cardI }))
    .catch(() => errorSend(res));
} 
return res.status(403).send({ message: 'Вы не имеете доступ к удалению чужих карточек' });

2020-01-26 10:53 UTC, aarefiev requested changes
Все очень круто. Теперь все работает почти как нужно и работа почти принята. 

В результате последних изменений возникли ошибки. Я их подробно осветил под списком **Можно лучше** и в комментариях в коде.

**Нужно исправить:**
1. Ошибки линтинга.
2. При создании пользователя возвращается пароль.

**Можно лучше:**
1. Удалить неиспользуемое.

---

**Расширенный комментарий к ошибке "При создании пользователя возвращается пароль"**:

Эта ошибка появилась в результате последних изменений. А точнее вот в этом [коммите](https://github.com/MaximMaslovVik/14_sprint/pull/1/commits/357b9ed9d484b4ea098e40289c38918e1f7630aa). В этом коммите были исправлены ошибки линтинга, но немного сломалась логика.

При создании пользователя пароль не нужно возвращать. Поэтому, то что будет передано в `user` нужно обработать. Самый лучший вариант - это создать отдельный метод для модели, который будет отфильтровывать данные при вызове. Этот вариант самый лучший, потому что позволяет вызывать метод в разных участках кода. Чтобы его реализовать нужно добавить метод в модель [`User`](https://github.com/MaximMaslovVik/14_sprint/blob/dev/models/user.js):

```js
userSchema.methods.omitPrivate = function omitPrivate() {
  const obj = this.toObject();
  delete obj.password;
  return obj;
};
```

В этом методе удаляется пароль. Если в дальнейшем нужно будет убрать какие-то еще другие поля, то по аналогии с паролем можно продолжить. Также стоит обратить внимание, что метод сделан исключительно для ситуаций, когда стандартным механизмом нельзя скрыть поле - я имею ввиду, что здесь уже нельзя использовать `.select('-password')`.

**И самое главное - метод необходимо определить до экспорта модели.**

Далее заменить это:
https://github.com/MaximMaslovVik/14_sprint/blob/f615c508a8ec2d462227c64b633d4175c82c6b27/controllers/users.js#L32
на это:
```js
.then((user) => res.send({ data: user.omitPrivate() }))
```

Указанный выше код проходит линтинг без ошибок. Но перед сдачей рекомендую запустить еще раз линтер командой `npx eslint --ext .js .`

2020-01-26 10:53 UTC, aarefiev commented on secret.js
> +const { PORT = 3000 } = process.env;
Нужно исправить: ошибки линтинга.
При запуске линтера находятся ошибки в этом файле:
```bash
$ npx eslint --ext .js .

~/14_sprint/secret.js
  1:1  error  Expected 1 empty line after require statement not followed by another require  import/newline-after-import
  1:7  error  'express' is assigned a value but never used                                   no-unused-vars
  2:9  error  'PORT' is assigned a value but never used                                      no-unused-vars

✖ 3 problems (3 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

Чтобы убрать ошибки необходимо удалить эти две строчки. Они здесь не нужны.

2020-01-26 10:53 UTC, aarefiev commented on routes/users.js
> +router.post('/signin', login);
Можно лучше: удалить неиспользуемое.
Роут авторизации уже был назначен выше:
https://github.com/MaximMaslovVik/14_sprint/blob/080528a90bd2913742e9e12da5f5ff54d82079ec/app.js#L30
Повторно не нужно переопределять роут. Это может привести к ошибкам.

2020-01-27 17:25 UTC, aarefiev approved these changes
Принято 🎉 . Получилось очень круто.
Теперь остается поправить конфликты и смержить _pull-request_ в _master_.

2020-01-28 20:42 UTC, MaximMaslovVik commented
14 сдан

2020-01-28 20:42 UTC, closed without merging